spring:
  messages:
    basename: "appmessages"
    encoding: "UTF-8"
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library_db
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.changelogs
app:
    properties:
      locale: en
