spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/changelog-master.yml"
  sql:
    init:
#      mode: never
      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql

  jpa:
    generate-ddl: false
#    generate-ddl: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
#        format_sql: true
  jmx:
    enabled: true

logging:
  level:
    root: INFO
  file:
    name: "logs/application.log"
  pattern:
    file: "%date %level [%thread] [%file:%line] %msg%n"

management:
  server:
    port: 8080
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "metrics,health,logfile,prometheus"
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-components: always
      show-details: when-authorized
      roles: "ADMIN"
    logfile:
      enabled: true
    prometheus:
      enabled: true