spring:
  messages:
    basename: "appmessages"
    encoding: "UTF-8"
  datasource:
    url: jdbc:h2:mem:library
    driverClassName: org.h2.Driver
    username: admin
    password: qwerty
  h2:
    console:
      path: /h2-console
      settings:
          web-allow-others: true
  liquibase:
    change-log: "classpath:/db/changelog/changelog-master.yml"
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO
app:
    properties:
      locale: en