server:
  port: 9001
spring:
  application:
    name: library-service
  datasource:
    url: jdbc:h2:mem:library;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: admin
    password: qwerty
  h2:
    console:
      path: /h2
      settings:
          web-allow-others: true
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/changelog-master.yml"
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  server:
    eviction-interval-timer-in-ms: 15000
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    instance-id: "${spring.application.name}:${server.port}"
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"